title = "Bahruz Jabiyev"
baseURL = "https://bahruz.me"
theme = "hugo-researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  description = "Bahruz Jabiyev's personal website"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "Powered by Hugo"
    url = "https://github.com/ojroques/hugo-researcher"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
